spring:
  application:
    name: userserv
  datasource:
    url: jdbc:postgresql://postgres-db:5432/mydatabase
    #    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mypassword
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  output:
    ansi:
      enabled: ALWAYS
